Set fso = CreateObject("Scripting.FileSystemObject")
maindir = fso.GetParentFolderName(WScript.ScriptFullName)

WScript.StdOut.WriteLine "  [1/5] Saison 2026 ..."
outpath = maindir & "\saison2026\index.html"
Set f = fso.CreateTextFile(outpath, True, True)
f.WriteLine "<!DOCTYPE html>"
f.WriteLine "<html lang=""de"">"
f.WriteLine "<head>"
f.WriteLine "  <meta charset=""UTF-8"">"
f.WriteLine "  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
f.WriteLine "  <title>Saison 2026 - Graue Pumas</title>"
f.WriteLine "  <link href=""https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Source+Sans+3:wght@300;400;600&display=swap"" rel=""stylesheet"">"
f.WriteLine "  <style>"
f.WriteLine "    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}"
f.WriteLine "    body{font-family:""Source Sans 3"",sans-serif;background:#faf7f2;color:#1e1e1e}"
f.WriteLine "    header{background:#1a3d2b}"
f.WriteLine "    header::after{content:"""";display:block;height:4px;background:linear-gradient(90deg,#c9a84c,#e9c46a,#c9a84c)}"
f.WriteLine "    .hi{max-width:800px;margin:0 auto;padding:1.5rem}"
f.WriteLine "    .back{display:block;font-size:.83rem;font-weight:600;color:#e9c46a;text-decoration:none;margin-bottom:1rem}"
f.WriteLine "    h1{font-family:""Playfair Display"",serif;font-size:1.8rem;font-weight:700;color:#fff}"
f.WriteLine "    .sub{font-size:.82rem;color:rgba(255,255,255,.55);margin-top:.2rem}"
f.WriteLine "    main{max-width:800px;margin:1.8rem auto 3rem;padding:0 1rem}"
f.WriteLine "    .lbl{font-size:.72rem;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#2d6a4f;margin-bottom:.8rem}"
f.WriteLine "    ul{list-style:none;display:flex;flex-direction:column;gap:.6rem}"
f.WriteLine "    li a{display:flex;align-items:center;gap:1rem;background:#fff;border:1px solid #e8e2d8;border-radius:10px;padding:1rem 1.2rem;text-decoration:none;color:#1e1e1e}"
f.WriteLine "    li a:hover{transform:translateX(4px);border-color:#52b788}"
f.WriteLine "    .badge{flex-shrink:0;width:38px;height:38px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:.65rem;font-weight:700;color:#fff}"
f.WriteLine "    .pdf{background:linear-gradient(135deg,#c0392b,#e74c3c)}"
f.WriteLine "    .jpg{background:linear-gradient(135deg,#1a6b8a,#2196b0)}"
f.WriteLine "    .fn{font-size:.97rem;font-weight:600;color:#1a3d2b;flex:1}"
f.WriteLine "    footer{text-align:center;padding:1.5rem;font-size:.78rem;color:#5a5a5a;border-top:1px solid #e8e2d8}"
f.WriteLine "  </style>"
f.WriteLine "</head>"
f.WriteLine "<body>"
f.WriteLine "<header>"
f.WriteLine "  <div class=""hi"">"
f.WriteLine "    <a class=""back"" href=""../index.html"">&larr; Zur&uuml;ck zur &Uuml;bersicht</a>"
f.WriteLine "    <h1>Saison 2026</h1>"
f.WriteLine "    <div class=""sub"">Dokumente und Informationen zur Saison</div>"
f.WriteLine "  </div>"
f.WriteLine "</header>"
f.WriteLine "<main>"
f.WriteLine "  <p class=""lbl"">Dateien</p>"
f.WriteLine "  <ul>"
Set folder = fso.GetFolder(maindir & "\saison2026")
For Each fil In folder.Files
  ext = LCase(fso.GetExtensionName(fil.Name))
  If ext = "pdf" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge pdf" & Chr(34) & ">PDF</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
  If ext = "jpg" Or ext = "jpeg" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge jpg" & Chr(34) & ">JPG</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
Next
f.WriteLine "  </ul>"
f.WriteLine "</main>"
f.WriteLine "<footer>&copy; 2026 &middot; Golfclub Tegernbach &middot; Graue Pumas</footer>"
f.WriteLine "</body>"
f.WriteLine "</html>"
f.Close
WScript.StdOut.WriteLine "  OK"

WScript.StdOut.WriteLine "  [2/5] Startlisten ..."
outpath = maindir & "\startlisten\index.html"
Set f = fso.CreateTextFile(outpath, True, True)
f.WriteLine "<!DOCTYPE html>"
f.WriteLine "<html lang=""de"">"
f.WriteLine "<head>"
f.WriteLine "  <meta charset=""UTF-8"">"
f.WriteLine "  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
f.WriteLine "  <title>Startlisten - Graue Pumas</title>"
f.WriteLine "  <link href=""https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Source+Sans+3:wght@300;400;600&display=swap"" rel=""stylesheet"">"
f.WriteLine "  <style>"
f.WriteLine "    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}"
f.WriteLine "    body{font-family:""Source Sans 3"",sans-serif;background:#faf7f2;color:#1e1e1e}"
f.WriteLine "    header{background:#1a3d2b}"
f.WriteLine "    header::after{content:"""";display:block;height:4px;background:linear-gradient(90deg,#c9a84c,#e9c46a,#c9a84c)}"
f.WriteLine "    .hi{max-width:800px;margin:0 auto;padding:1.5rem}"
f.WriteLine "    .back{display:block;font-size:.83rem;font-weight:600;color:#e9c46a;text-decoration:none;margin-bottom:1rem}"
f.WriteLine "    h1{font-family:""Playfair Display"",serif;font-size:1.8rem;font-weight:700;color:#fff}"
f.WriteLine "    .sub{font-size:.82rem;color:rgba(255,255,255,.55);margin-top:.2rem}"
f.WriteLine "    main{max-width:800px;margin:1.8rem auto 3rem;padding:0 1rem}"
f.WriteLine "    .lbl{font-size:.72rem;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#2d6a4f;margin-bottom:.8rem}"
f.WriteLine "    ul{list-style:none;display:flex;flex-direction:column;gap:.6rem}"
f.WriteLine "    li a{display:flex;align-items:center;gap:1rem;background:#fff;border:1px solid #e8e2d8;border-radius:10px;padding:1rem 1.2rem;text-decoration:none;color:#1e1e1e}"
f.WriteLine "    li a:hover{transform:translateX(4px);border-color:#52b788}"
f.WriteLine "    .badge{flex-shrink:0;width:38px;height:38px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:.65rem;font-weight:700;color:#fff}"
f.WriteLine "    .pdf{background:linear-gradient(135deg,#c0392b,#e74c3c)}"
f.WriteLine "    .jpg{background:linear-gradient(135deg,#1a6b8a,#2196b0)}"
f.WriteLine "    .fn{font-size:.97rem;font-weight:600;color:#1a3d2b;flex:1}"
f.WriteLine "    footer{text-align:center;padding:1.5rem;font-size:.78rem;color:#5a5a5a;border-top:1px solid #e8e2d8}"
f.WriteLine "  </style>"
f.WriteLine "</head>"
f.WriteLine "<body>"
f.WriteLine "<header>"
f.WriteLine "  <div class=""hi"">"
f.WriteLine "    <a class=""back"" href=""../index.html"">&larr; Zur&uuml;ck zur &Uuml;bersicht</a>"
f.WriteLine "    <h1>Startlisten</h1>"
f.WriteLine "    <div class=""sub"">Aktuelle Startlisten als PDF</div>"
f.WriteLine "  </div>"
f.WriteLine "</header>"
f.WriteLine "<main>"
f.WriteLine "  <p class=""lbl"">Dateien</p>"
f.WriteLine "  <ul>"
Set folder = fso.GetFolder(maindir & "\startlisten")
For Each fil In folder.Files
  ext = LCase(fso.GetExtensionName(fil.Name))
  If ext = "pdf" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge pdf" & Chr(34) & ">PDF</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
  If ext = "jpg" Or ext = "jpeg" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge jpg" & Chr(34) & ">JPG</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
Next
f.WriteLine "  </ul>"
f.WriteLine "</main>"
f.WriteLine "<footer>&copy; 2026 &middot; Golfclub Tegernbach &middot; Graue Pumas</footer>"
f.WriteLine "</body>"
f.WriteLine "</html>"
f.Close
WScript.StdOut.WriteLine "  OK"

WScript.StdOut.WriteLine "  [3/5] Ergebnisse ..."
outpath = maindir & "\ergebnisse\index.html"
Set f = fso.CreateTextFile(outpath, True, True)
f.WriteLine "<!DOCTYPE html>"
f.WriteLine "<html lang=""de"">"
f.WriteLine "<head>"
f.WriteLine "  <meta charset=""UTF-8"">"
f.WriteLine "  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
f.WriteLine "  <title>Ergebnisse - Graue Pumas</title>"
f.WriteLine "  <link href=""https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Source+Sans+3:wght@300;400;600&display=swap"" rel=""stylesheet"">"
f.WriteLine "  <style>"
f.WriteLine "    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}"
f.WriteLine "    body{font-family:""Source Sans 3"",sans-serif;background:#faf7f2;color:#1e1e1e}"
f.WriteLine "    header{background:#1a3d2b}"
f.WriteLine "    header::after{content:"""";display:block;height:4px;background:linear-gradient(90deg,#c9a84c,#e9c46a,#c9a84c)}"
f.WriteLine "    .hi{max-width:800px;margin:0 auto;padding:1.5rem}"
f.WriteLine "    .back{display:block;font-size:.83rem;font-weight:600;color:#e9c46a;text-decoration:none;margin-bottom:1rem}"
f.WriteLine "    h1{font-family:""Playfair Display"",serif;font-size:1.8rem;font-weight:700;color:#fff}"
f.WriteLine "    .sub{font-size:.82rem;color:rgba(255,255,255,.55);margin-top:.2rem}"
f.WriteLine "    main{max-width:800px;margin:1.8rem auto 3rem;padding:0 1rem}"
f.WriteLine "    .lbl{font-size:.72rem;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#2d6a4f;margin-bottom:.8rem}"
f.WriteLine "    ul{list-style:none;display:flex;flex-direction:column;gap:.6rem}"
f.WriteLine "    li a{display:flex;align-items:center;gap:1rem;background:#fff;border:1px solid #e8e2d8;border-radius:10px;padding:1rem 1.2rem;text-decoration:none;color:#1e1e1e}"
f.WriteLine "    li a:hover{transform:translateX(4px);border-color:#52b788}"
f.WriteLine "    .badge{flex-shrink:0;width:38px;height:38px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:.65rem;font-weight:700;color:#fff}"
f.WriteLine "    .pdf{background:linear-gradient(135deg,#c0392b,#e74c3c)}"
f.WriteLine "    .jpg{background:linear-gradient(135deg,#1a6b8a,#2196b0)}"
f.WriteLine "    .fn{font-size:.97rem;font-weight:600;color:#1a3d2b;flex:1}"
f.WriteLine "    footer{text-align:center;padding:1.5rem;font-size:.78rem;color:#5a5a5a;border-top:1px solid #e8e2d8}"
f.WriteLine "  </style>"
f.WriteLine "</head>"
f.WriteLine "<body>"
f.WriteLine "<header>"
f.WriteLine "  <div class=""hi"">"
f.WriteLine "    <a class=""back"" href=""../index.html"">&larr; Zur&uuml;ck zur &Uuml;bersicht</a>"
f.WriteLine "    <h1>Ergebnisse</h1>"
f.WriteLine "    <div class=""sub"">Turnierergebnisse als PDF</div>"
f.WriteLine "  </div>"
f.WriteLine "</header>"
f.WriteLine "<main>"
f.WriteLine "  <p class=""lbl"">Dateien</p>"
f.WriteLine "  <ul>"
Set folder = fso.GetFolder(maindir & "\ergebnisse")
For Each fil In folder.Files
  ext = LCase(fso.GetExtensionName(fil.Name))
  If ext = "pdf" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge pdf" & Chr(34) & ">PDF</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
  If ext = "jpg" Or ext = "jpeg" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge jpg" & Chr(34) & ">JPG</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
Next
f.WriteLine "  </ul>"
f.WriteLine "</main>"
f.WriteLine "<footer>&copy; 2026 &middot; Golfclub Tegernbach &middot; Graue Pumas</footer>"
f.WriteLine "</body>"
f.WriteLine "</html>"
f.Close
WScript.StdOut.WriteLine "  OK"

WScript.StdOut.WriteLine "  [4/5] Fotos ..."
outpath = maindir & "\fotos\index.html"
Set f = fso.CreateTextFile(outpath, True, True)
f.WriteLine "<!DOCTYPE html>"
f.WriteLine "<html lang=""de"">"
f.WriteLine "<head>"
f.WriteLine "  <meta charset=""UTF-8"">"
f.WriteLine "  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
f.WriteLine "  <title>Fotos - Graue Pumas</title>"
f.WriteLine "  <link href=""https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Source+Sans+3:wght@300;400;600&display=swap"" rel=""stylesheet"">"
f.WriteLine "  <style>"
f.WriteLine "    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}"
f.WriteLine "    body{font-family:""Source Sans 3"",sans-serif;background:#faf7f2;color:#1e1e1e}"
f.WriteLine "    header{background:#1a3d2b}"
f.WriteLine "    header::after{content:"""";display:block;height:4px;background:linear-gradient(90deg,#c9a84c,#e9c46a,#c9a84c)}"
f.WriteLine "    .hi{max-width:800px;margin:0 auto;padding:1.5rem}"
f.WriteLine "    .back{display:block;font-size:.83rem;font-weight:600;color:#e9c46a;text-decoration:none;margin-bottom:1rem}"
f.WriteLine "    h1{font-family:""Playfair Display"",serif;font-size:1.8rem;font-weight:700;color:#fff}"
f.WriteLine "    .sub{font-size:.82rem;color:rgba(255,255,255,.55);margin-top:.2rem}"
f.WriteLine "    main{max-width:800px;margin:1.8rem auto 3rem;padding:0 1rem}"
f.WriteLine "    .lbl{font-size:.72rem;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#2d6a4f;margin-bottom:.8rem}"
f.WriteLine "    ul{list-style:none;display:flex;flex-direction:column;gap:.6rem}"
f.WriteLine "    li a{display:flex;align-items:center;gap:1rem;background:#fff;border:1px solid #e8e2d8;border-radius:10px;padding:1rem 1.2rem;text-decoration:none;color:#1e1e1e}"
f.WriteLine "    li a:hover{transform:translateX(4px);border-color:#52b788}"
f.WriteLine "    .badge{flex-shrink:0;width:38px;height:38px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:.65rem;font-weight:700;color:#fff}"
f.WriteLine "    .pdf{background:linear-gradient(135deg,#c0392b,#e74c3c)}"
f.WriteLine "    .jpg{background:linear-gradient(135deg,#1a6b8a,#2196b0)}"
f.WriteLine "    .fn{font-size:.97rem;font-weight:600;color:#1a3d2b;flex:1}"
f.WriteLine "    footer{text-align:center;padding:1.5rem;font-size:.78rem;color:#5a5a5a;border-top:1px solid #e8e2d8}"
f.WriteLine "  </style>"
f.WriteLine "</head>"
f.WriteLine "<body>"
f.WriteLine "<header>"
f.WriteLine "  <div class=""hi"">"
f.WriteLine "    <a class=""back"" href=""../index.html"">&larr; Zur&uuml;ck zur &Uuml;bersicht</a>"
f.WriteLine "    <h1>Fotos</h1>"
f.WriteLine "    <div class=""sub"">Bilder aus dem Clubgeschehen</div>"
f.WriteLine "  </div>"
f.WriteLine "</header>"
f.WriteLine "<main>"
f.WriteLine "  <p class=""lbl"">Dateien</p>"
f.WriteLine "  <ul>"
Set folder = fso.GetFolder(maindir & "\fotos")
For Each fil In folder.Files
  ext = LCase(fso.GetExtensionName(fil.Name))
  If ext = "pdf" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge pdf" & Chr(34) & ">PDF</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
  If ext = "jpg" Or ext = "jpeg" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge jpg" & Chr(34) & ">JPG</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
Next
f.WriteLine "  </ul>"
f.WriteLine "</main>"
f.WriteLine "<footer>&copy; 2026 &middot; Golfclub Tegernbach &middot; Graue Pumas</footer>"
f.WriteLine "</body>"
f.WriteLine "</html>"
f.Close
WScript.StdOut.WriteLine "  OK"

WScript.StdOut.WriteLine "  [5/5] Sonstiges ..."
outpath = maindir & "\sonstiges\index.html"
Set f = fso.CreateTextFile(outpath, True, True)
f.WriteLine "<!DOCTYPE html>"
f.WriteLine "<html lang=""de"">"
f.WriteLine "<head>"
f.WriteLine "  <meta charset=""UTF-8"">"
f.WriteLine "  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
f.WriteLine "  <title>Sonstiges - Graue Pumas</title>"
f.WriteLine "  <link href=""https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Source+Sans+3:wght@300;400;600&display=swap"" rel=""stylesheet"">"
f.WriteLine "  <style>"
f.WriteLine "    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}"
f.WriteLine "    body{font-family:""Source Sans 3"",sans-serif;background:#faf7f2;color:#1e1e1e}"
f.WriteLine "    header{background:#1a3d2b}"
f.WriteLine "    header::after{content:"""";display:block;height:4px;background:linear-gradient(90deg,#c9a84c,#e9c46a,#c9a84c)}"
f.WriteLine "    .hi{max-width:800px;margin:0 auto;padding:1.5rem}"
f.WriteLine "    .back{display:block;font-size:.83rem;font-weight:600;color:#e9c46a;text-decoration:none;margin-bottom:1rem}"
f.WriteLine "    h1{font-family:""Playfair Display"",serif;font-size:1.8rem;font-weight:700;color:#fff}"
f.WriteLine "    .sub{font-size:.82rem;color:rgba(255,255,255,.55);margin-top:.2rem}"
f.WriteLine "    main{max-width:800px;margin:1.8rem auto 3rem;padding:0 1rem}"
f.WriteLine "    .lbl{font-size:.72rem;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#2d6a4f;margin-bottom:.8rem}"
f.WriteLine "    ul{list-style:none;display:flex;flex-direction:column;gap:.6rem}"
f.WriteLine "    li a{display:flex;align-items:center;gap:1rem;background:#fff;border:1px solid #e8e2d8;border-radius:10px;padding:1rem 1.2rem;text-decoration:none;color:#1e1e1e}"
f.WriteLine "    li a:hover{transform:translateX(4px);border-color:#52b788}"
f.WriteLine "    .badge{flex-shrink:0;width:38px;height:38px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:.65rem;font-weight:700;color:#fff}"
f.WriteLine "    .pdf{background:linear-gradient(135deg,#c0392b,#e74c3c)}"
f.WriteLine "    .jpg{background:linear-gradient(135deg,#1a6b8a,#2196b0)}"
f.WriteLine "    .fn{font-size:.97rem;font-weight:600;color:#1a3d2b;flex:1}"
f.WriteLine "    footer{text-align:center;padding:1.5rem;font-size:.78rem;color:#5a5a5a;border-top:1px solid #e8e2d8}"
f.WriteLine "  </style>"
f.WriteLine "</head>"
f.WriteLine "<body>"
f.WriteLine "<header>"
f.WriteLine "  <div class=""hi"">"
f.WriteLine "    <a class=""back"" href=""../index.html"">&larr; Zur&uuml;ck zur &Uuml;bersicht</a>"
f.WriteLine "    <h1>Sonstiges</h1>"
f.WriteLine "    <div class=""sub"">Weitere Dokumente als PDF</div>"
f.WriteLine "  </div>"
f.WriteLine "</header>"
f.WriteLine "<main>"
f.WriteLine "  <p class=""lbl"">Dateien</p>"
f.WriteLine "  <ul>"
Set folder = fso.GetFolder(maindir & "\sonstiges")
For Each fil In folder.Files
  ext = LCase(fso.GetExtensionName(fil.Name))
  If ext = "pdf" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge pdf" & Chr(34) & ">PDF</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
  If ext = "jpg" Or ext = "jpeg" Then
    f.WriteLine "    <li><a href=" & Chr(34) & fil.Name & Chr(34) & " target=" & Chr(34) & "_blank" & Chr(34) & "><div class=" & Chr(34) & "badge jpg" & Chr(34) & ">JPG</div><span class=" & Chr(34) & "fn" & Chr(34) & ">" & fil.Name & "</span><span>&nearr;</span></a></li>"
  End If
Next
f.WriteLine "  </ul>"
f.WriteLine "</main>"
f.WriteLine "<footer>&copy; 2026 &middot; Golfclub Tegernbach &middot; Graue Pumas</footer>"
f.WriteLine "</body>"
f.WriteLine "</html>"
f.Close
WScript.StdOut.WriteLine "  OK"
